### ISSUE TITLE
Isolation Segments Not Correctly Displayed

### ISSUE THREAD

**Issue by r0bm3** [ECSTeam/cloudfoundry-top-plugin#12] opened 2018-08-29 17:20 UTC
We're seeing an issue inside of the current master branch where the isolation segments displayed for apps is the CF default "shared" segment, and not the one that is associated/applied to the ORG.

We've been able to verify this by inspecting the output of: cf curl /v2/apps/[app_guid]/stats and inspecting the "isolation_segment" value that is returned.

**Comment by kkellner** [comment] 2019-07-22 17:14
The issue is that `cf top` was looking only at the space's assigned iso seg.  If it was not set, show the "default" which `cf top` assumed was "shared".   This is incorrect as an org can set the default for the entire org.   What should occur is that if an iso seg is not defined on a space, we need to look to see if the containing org has a default iso seg assigned,  if it does, then show the org's default iso seg, if not, it must be "shared".

This has been fixed in v0.9.4 of `cf top`.

**Closed** 2019-07-22 17:14 UTC

**Comment by skertz** [comment] 2020-05-22 19:28
I'm seeing the same problem in v0.9.5 where my cells are displaying "shared" 
![image](https://user-images.githubusercontent.com/15638057/82702849-a12d9c80-9c27-11ea-90e6-fa5eef582019.png)
